name = "stratus"
version = "1.0.0-rc1"

description = "A Gleam WebSocket client"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "stratus" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = "1.0.0-rc1"
gleam_otp = "1.0.0-rc3"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gramps = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
repeatedly = ">= 2.1.0 and < 3.0.0"
birl = ">= 1.5.0 and < 2.0.0"
