name = "stratus"
version = "1.0.2"

description = "A Gleam WebSocket client"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "stratus" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gramps = ">= 5.0.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
