name = "stratus"
version = "0.2.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A Gleam WebSocket client"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "stratus" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = "~> 0.24"
gleam_otp = "~> 0.9"
gleam_http = "~> 3.5"
gleam_crypto = "~> 1.3"
gramps = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
repeatedly = "~> 2.1"
birl = "~> 1.5"
